//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPWebApplication.Dao
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmallERPEntities : DbContext
    {
        public SmallERPEntities()
            : base("name=SmallERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BSSupplier> BSSupplier { get; set; }
        public virtual DbSet<PUInStore> PUInStore { get; set; }
        public virtual DbSet<PUOrder> PUOrder { get; set; }
        public virtual DbSet<PUPay> PUPay { get; set; }
        public virtual DbSet<SEGather> SEGather { get; set; }
        public virtual DbSet<SEOrder> SEOrder { get; set; }
        public virtual DbSet<SEOutStore> SEOutStore { get; set; }
    }
}
