//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPWebApplication.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUOrder
    {
        /// <summary>
        /// 单据编号
        /// </summary>
        public string PUOrderCode { get; set; }
        /// <summary>
        /// 单据日期
        /// </summary>
        public Nullable<System.DateTime> PUOrderDate { get; set; }
        /// <summary>
        /// 操作员
        /// </summary>
        public string OperatorCode { get; set; }
        /// <summary>
        /// 供应商
        /// </summary>
        public string SupplierCode { get; set; }
        /// <summary>
        /// 订货仓库
        /// </summary>
        public string StoreCode { get; set; }
        /// <summary>
        /// 存货编号
        /// </summary>
        public string InvenCode { get; set; }
        /// <summary>
        /// 采购单价
        /// </summary>
        public Nullable<decimal> UnitPrice { get; set; }
        /// <summary>
        /// 采购数量
        /// </summary>
        public Nullable<int> Quantity { get; set; }
        /// <summary>
        /// 采购金额
        /// </summary>
        public Nullable<decimal> PUMoney { get; set; }
        /// <summary>
        /// 收货日期
        /// </summary>
        public Nullable<System.DateTime> RecInvenDate { get; set; }
        /// <summary>
        /// 采购员
        /// </summary>
        public string EmployeeCode { get; set; }
        /// <summary>
        /// 审核状态
        /// </summary>
        public Nullable<bool> IsFlag { get; set; }
    
        public virtual BSSupplier BSSupplier { get; set; }
    }
}
