//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPWebApplication.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEOrder
    {
        public string SEOrderCode { get; set; }
        public Nullable<System.DateTime> SEOrderDate { get; set; }
        public string OperatorCode { get; set; }
        public string CustomerCode { get; set; }
        public string StoreCode { get; set; }
        public string InvenCode { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> SEMoney { get; set; }
        public Nullable<System.DateTime> SenInvenDate { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<bool> IsFlag { get; set; }
    }
}
